config/routes.rb
Zen::Application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => 'registrations'}
  
  resources :users, :only => [:show, :update]
  get 'account' => 'users#edit'
  get 'account/password' => 'users#password'
  get 'subscription' => "users#subscription"
  
  resources :projects do
    collection do
      get 'completed'
    end
    
    resources :transitions, :except => :destroy
  end
  
  resources :metrics, :only => :index

  root :to => 'site#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :invite_code
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :invite_code
  
  
  has_many :projects, :dependent => :destroy
  has_many :transitions
  
  validates :name, :presence => true
  validates :email, :uniqueness => { :case_sensitive => false }
  validates :invite_code, :inclusion => { :in => ['LECAMPING','GARDEN','lecamping','garden'], :message => "%{value} is not valid" }, :on => :create
  
  def is_admin?
    id == 1
  end
    
  def free_projects
    d = Settings.free_projects - projects.count
    d > 0 ? d : 0
  end

  def active_projects_value
    projects.sum(:exact_value, :conditions => {:aasm_state => [:lead, :pitch, :negotiation, :closing]})
    #projects.map(&:exact_value).compact.inject(0,:+)
  end
  
  def active_projects_count
    projects.count(:conditions => {:aasm_state => [:lead, :pitch, :negotiation, :closing]})
  end
  
  def all_time_projects_count
    projects.count
  end
  
  def active_projects_average_value
    active_projects_count == 0 ? 0 : active_projects_value / active_projects_count
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  def index
    redirect_to account_edit_path
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to account_path
      return
    else
      render 'edit'
    end
  end
  
  def password
    @user = current_user
  end
  
  def subscription
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def error_messages!
    return "" if @user.errors.empty?
    messages = @user.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved", :count => @user.errors.count, :resource => "user")
    
    html = <<-HTML
      <div id="error_explanation">
        <h2>#{sentence}</h2>
        <ul>#{messages}</ul>
      </div>
    HTML
      
    html.html_safe
  end
  
end

app/views/users/_sidebar.html.erb
<div id="sidebar">
	<div class="wrapper">
		<div class="nav">
		  <ul>
			<li><%= link_to 'My Account',account_path %></li>
			<li><%= link_to 'Update Password',account_password_path %></li>
			<li><%= link_to 'Billing',subscription_path %></li>
		  </ul>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<h1>My Account</h1>
<div class="main-content">
  <div class="header">&nbsp;</div>
  <div class="inner">
    <%= form_for @user do |f| %>
	<%= error_messages! %>
	<ul>
	   <li>
		 <%= f.label :name %>
		 <%= f.text_field :name, :required => true %>
	   </li>
       <li>
		 <%= f.label :email %>
	     <%= f.text_field :email, :required => true %>
	   </li>
       <li><%= f.submit "Update", :class => "button" %></li>
	</ul>
    <% end %>
   </div>
</div>

<%= render 'users/sidebar' %>

app/views/users/password.html.erb
<h1>Update password</h1>
<div class="main-content">
  <div class="header">&nbsp;</div>
  <div class="inner">
    <%= form_for @user, :url => registration_path(@user), :html => { :method => :put} do |f| %>
	<%= devise_error_messages! if defined? resource %>
	<ul>
       <li>
		 <%= f.label :password %>
	     <%= f.password_field :password, :required => true  %>
	   </li>
	   <li>
		 <%= f.label :password_confirmation %>
         <%= f.password_field :password_confirmation, :required => true  %>
	   </li>
	   <li>
		 <%= f.label :current_password %>
	     <%= f.password_field :current_password, :required => true  %>
	   </li>
       <li><%= f.submit :value=> 'Update Password', :class => "button" %></li>
	</ul>
    <% end %>
   </div>
</div>

<%= render 'users/sidebar' %>

app/views/users/subscription.html.erb
<h1>Billing</h1>
<div class="main-content">
  <div class="header">&nbsp;</div>
  <div class="inner">
	<form action="#">
	<ul>
		<li class="empty">
			The billing process is disabled for the moment.
		</li>
	</ul>
	</form>
  </div>
</div>

<%= render 'users/sidebar' %>