config/routes.rb
Zen::Application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => 'registrations'}
  
  resources :users, :only => [:show, :update]
  get 'account' => 'users#edit'
  get 'account/password' => 'users#password'
  get 'subscription' => "users#subscription"
  
  resources :projects do
    collection do
      get 'completed'
    end
    
    resources :transitions, :except => :destroy
  end
  
  resources :metrics, :only => :index

  root :to => 'site#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :client, :exact_value, :estimate_value, :state
  belongs_to :user
  has_many :transitions, :dependent => :delete_all
  
  include AASM
  aasm_initial_state :lead
  aasm_state :lead
  aasm_state :pitch
  aasm_state :negotiation
  aasm_state :closing
  aasm_state :won
  aasm_state :lost
  aasm_state :hold
  
  aasm_event :enter_lead do
    transitions :to => :lead, :from => [:pitch, :negotiation, :closing, :hold]
  end
  
  aasm_event :enter_pitch do
    transitions :to => :pitch, :from => [:lead, :negotiation, :closing, :hold]
  end
  
  aasm_event :enter_negotiation do
    transitions :to => :negotiation, :from => [:lead, :pitch, :closing, :hold]
  end
  
  aasm_event :enter_closing do
    transitions :to => :closing, :from => [:lead, :pitch, :negotiation, :hold, :won, :lost]
  end
  
  aasm_event :enter_won do
    transitions :to => :won, :from => [:lead, :pitch, :negotiation, :closing]
  end
  
  aasm_event :enter_lost do
    transitions :to => :lost, :from => [:lead, :pitch, :negotiation, :closing]
  end
  
  aasm_event :enter_hold do
    transitions :to => :hold, :from => [:lead, :pitch, :negotiation, :closing]
  end
  
  def value
    exact_value || ('$' * (estimate_value || 0))
  end
  
  def self.ordered_states
    [:lead, :pitch, :negotiation, :closing, :won]
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource :through => :current_user
  
  def index
    @project = Project.new
    @projects = current_user.projects.where({:aasm_state => [:lead, :pitch, :negotiation, :closing, :hold]}).order('created_at DESC')
    @free_projects = current_user.free_projects
    @active_projects_value = current_user.active_projects_value
    @active_projects_count = current_user.active_projects_count
  end
  
  def create
    if current_user.projects.count < Settings.free_projects
    @project = current_user.projects.build(params[:project])
    if @project.valid?
      @project.save
      @transition = @project.transitions.build({:user_id => current_user.id, :enter_state => "lead"})
      if @transition.valid?
        @transition.save
      else
        render :nothing => true, :status => 500 and return if request.xhr?
        redirect_to projects_path and return
      end
      render :partial => 'project', :locals => { :project => @project, :projects_stats => true }, :layout => false and return if request.xhr? 
      redirect_to projects_path
    end
    else
      render :partial => 'limit_reached' and return if request.xhr?
      redirect_to projects_path, :notice => "You reached the free project limit."
    end
  end

  def update
    if @project.update_attributes(params[:project]) 
      render :partial => 'project', :locals => { :project => @project, :projects_stats => true }, :layout => false and return if request.xhr?
      redirect_to project_path(@project)
    end
  end
  
  def show
    @completed_transitions = @project.transitions.where("exit_state IS NOT NULL").order("created_at DESC")
    @new_transition = Transition.new
  end
  
  def destroy
    @project.destroy
    render :partial => 'project', :locals => { :project => @project, :projects_stats => true }, :layout => false and return if request.xhr?
    redirect_to projects_path
  end
  
  def completed
    @projects = current_user.projects.where({:aasm_state => [:lost, :won]}).order("created_at DESC")
  end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def transition_tag(enter_state, exit_state)
    raw "#{enter_state.capitalize} &rarr; #{exit_state.capitalize}"
  end
  
  def project_states(project)
    states = Project.ordered_states
    list = ''
    css_class = ''
    current_index = states.index(project.aasm_state.to_sym) || -1
    states.each_with_index do |state, idx|
      css_class = idx < current_index ? 'past' : idx == current_index ? 'current' : ''
      list = list + "<li class=\"pos-#{idx+1} #{css_class}\" data-state=\"#{state.to_s}\">#{state.to_s.capitalize}</li>"
    end
    raw "<ol class=\"states\">#{list}</ol>"
  end
  
  def formatted_exact_value(value)
    number_with_precision(value, :precision => 2, :strip_insignificant_zeros => true)
  end
  
  def formatted_estimate_value(value)
    raw(Settings.estimate_tag * (value || 0))
  end
  
  def formatted_value(project)
    if project.exact_value
      formatted_exact_value(project.exact_value)
    elsif project.estimate_value
      formatted_estimate_value(project.estimate_value)
    end
  end
end

app/views/projects/_edit_modal.html.erb
<div class="modal" id="edit_project_modal">
<%= form_for @project do |f| %>
  <div class="modal-header">
    <h3>Deal Details</h3>
  </div>
  <div class="modal-body">
    <ul>
		<li><%= f.label :name %> <%= f.text_field :name, :autocomplete => "off" %></li>
		<li><%= f.label :client %> <%= f.text_field :client, :autocomplete => "off" %></li>
		<li class="value">
			<%= f.label :exact_value %> <%= f.text_field :exact_value, :autocomplete => "off" %> 
			<span>&ndash; or &ndash;</span>
			<div class="estimate <%= "estimated_#{@project.estimate_value}" if @project.estimate_value %>">
				<% 1.upto(5) do |i| %>
					<%= link_to raw(Settings.estimate_tag),'#', :class => "estimate_#{i}", :"data-value" => i %>
				<% end %>
			</div>
			<%= f.hidden_field :estimate_value %>
		</li>
	</ul>
  </div>
  <div class="modal-footer">
	<button type="submit" class="button">Save Deal</button>
    <a href="#" data-dismiss="modal">Cancel</a> 
  </div>
<% end %>
</div>

app/views/projects/_limit_reached.html.erb
<div class="limit">
 You reached the free projects limit. Upgrade now to get unlimited projects ?
</div>

app/views/projects/_new_modal.html.erb
<div class="modal" id="new_project_modal">
<%= form_for @project do |f| %>
  <div class="modal-header">
    <h3>Deal Details</h3>
  </div>
  <div class="modal-body">
    <ul>
		<li><%= f.label :name %> <%= f.text_field :name, :autocomplete => "off" %></li>
		<li><%= f.label :client %> <%= f.text_field :client, :autocomplete => "off" %></li>
		<li class="value">
			<%= f.label :exact_value %> <%= f.text_field :exact_value, :autocomplete => "off" %> 
			<span>&ndash; or &ndash;</span>
			<div class="estimate">
				<% 1.upto(5) do |i| %>
					<%= link_to raw(Settings.estimate_tag),'#', :class => "estimate_#{i}", :"data-value" => i %>
				<% end %>
			</div>
			<%= f.hidden_field :estimate_value %>
		</li>
	</ul>
  </div>
  <div class="modal-footer">
	<button type="submit" class="button">Save Deal</button>
    <a href="#" data-dismiss="modal">Cancel</a> 
  </div>
<% end %>
</div>

app/views/projects/_note_modal.html.erb
<div class="modal" id="new_note_modal">
<%= form_for [@project,@new_transition] do |f| %>
  <div class="modal-header">
    <h3>New Note</h3>
  </div>
  <div class="modal-body">
	<div class="value">
    	<%= f.text_area :comment, :rows => 10, :cols => 40 %>
	</div>
  </div>
  <div class="modal-footer">
	<button type="submit" class="button">Add Note</button>
    <a href="#" data-dismiss="modal">Cancel</a>
  </div>
<% end %>
</div>

app/views/projects/_project.html.erb
<li class="project <%= 'hold' if project.hold? %>" id="project_<%= project.id %>" data-id="<%= project.id %>" data-name="<%= project.name %>" 
	data-client="<%= project.client %>" <%= raw "data-exact-value=\"#{project.exact_value}\"" if project.exact_value %>
	<%= raw "data-estimate-value=\"#{project.estimate_value}\"" if project.estimate_value %>>
	<h2>
		<%= link_to project.name, project_path(project), :class => 'project-name' %>
		<span class="project-client"><%= project.client %></span>
		<span class="deal-value"><%= formatted_value(project) %></span>
	</h2>
	<%= project_states(project) %>
	<div class="actions">
		<a href="#" rel="tooltip" class="hold" data-state="hold" title="Put on hold"><span>Pause</span></a>
		<a href="#" rel="tooltip" class="lost" data-state="lost" title="Mark deal as lost"><span>Lost</span></a>
		<a href="#" rel="tooltip" class="edit" title="Edit"><span>Edit</span></a>
		<a href="#" rel="tooltip" class="delete" title="Delete"><span>Delete</span></a>
	</div>
	<% if defined?(transition) && !project.hold? %>
	<div class="note">
		<%= form_for [project,transition] do |f| %>
			<%= f.text_area :comment, :placeholder => "Add a note for this change (optional)" %>
			<button type="submit" class="button">Add Note</button>
		    <a href="#" class="cancel">Cancel</a>
		<% end %>
	</div>
	<% end %>
	<% if project.hold? %>
	<div class="overlay">
		<div>
			<%= link_to "Reactivate this deal", "#", :class => "unhold", :"data-state" => "closing" %><br/>
			<%= link_to "View History", project_path(project), :class => "history" %>
		</div>
	</div>
	<% end %>
</li>
<% if defined? projects_stats %>
<div class="info">
  <span class="active-deals"><%= current_user.active_projects_count %></span>
  <span class="deals-value"><%= formatted_exact_value(current_user.active_projects_value) %></span>
  <span class="free-deals"><%= current_user.free_projects %></span>
</div>
<% end %>

app/views/projects/completed.html.erb
<h1>Completed Projects</h1>
<div class="main-content">
	<div class="header">
	 &nbsp;
	</div>
	<div class="inner">
		<ul class="completed-projects">
			<% @projects.each do |project| %>
				<li>
				  <h3><%= link_to project.name, project_path(project) %></h3>
				  <p><%= project.client %> &mdash; <%= project.value %></p>
				</li>
			<% end %>
			<% if @projects.empty? %>
			<li class="empty">It looks like you don’t have any completed deals.</li>
			<% end %>
		</ul>
	</div>
</div>
<div id="sidebar">
	<div class="wrapper">
		<div class="nav">
		  <ul>
			<li><%= link_to raw("&#9666; Back to Active Projects"),projects_path %></li>
		  </ul>
		</div>
	</div>
</div>

app/views/projects/index.html.erb
<h1>Projects</h1>

<div id="sidebar">
	<div class="wrapper">
		<div class="inner">
			<dl class="metrics">
				<dt>Active deals</dt>
				<dd class="projects-count"><%= @active_projects_count %></dd>
				<dt>Active deals value</dt>
				<dd class="projects-value"><%= formatted_exact_value(@active_projects_value) %></dd>
			</dl>
			<div class="buttons">
				<div class="button-container">
					<%= link_to 'More Metrics', metrics_path, :class => "button" %>
				</div>
			</div>
		</div>
	</div>
	
	<div class="wrapper">
		<div class="inner">
			<div class="subscription">
				<p>You've got <strong class="free-projects"><%= @free_projects %></strong> free projects left. Need more?</p>
				<div class="buttons">
					<div class="button-container">
						<%= link_to 'Upgrade Now', subscription_path, :class => "button" %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="projects" class="main-content">
	<div class="header">
		<%= link_to 'Add new deal', '#new_project_modal', :class => "button", :"data-toggle" => "modal" %>
		<form id="project-search-form" action="#">
			<input type="text" placeholder="Search Deals">
		</form>
	</div>
	<div class="inner">
		<ul class="projects ui-sortable">
			<% @projects.each do |project| %>
				<%= render :partial => 'project', :object => project %>
			<% end %>
			<% if @projects.empty? %>
			<li class="empty">It looks like you don’t have any active deals. <a href="#new_project_modal" data-toggle="modal">Add a deal.</a></li>
			<% end %>
		</ul>
	</div>
	<div class="footer">
		<div class="button-container">
			<%= link_to 'View Completed Deals', completed_projects_path, :class => "button" %>
		</div>
	</div>
</div>


<%= render :partial => "new_modal" %>

app/views/projects/project.html.erb
<%= render :partial => 'project', :object => @project %>

app/views/projects/show.html.erb
<h1>
  <%= @project.name %>
  <span class="project-client"><%= @project.client %></span>
  <span class="deal-value"><%= formatted_value(@project) %></span>
</h1>
<div id="projects" class="main-content">
	<div class="header">
	 <%= link_to 'Edit Deal', '#edit_project_modal', :class => "button", :"data-toggle" => "modal" %>
	</div>
	<div class="inner">
		<ul class="history">
			<% @completed_transitions.each do |transition| %>
				<li>
				  <div class="transition"><%= transition_tag transition.enter_state, transition.exit_state %></div>
				  <p><%= transition.comment %></p>
				  <div class="time"><%= time_ago_in_words transition.updated_at %></div>
				</li>
			<% end %>
			<% if @completed_transitions.empty? %>
			<li class="empty">This deal doesn't have any notes or history yet.</li>
			<% end %>
		</ul>
	</div>
</div>
<div id="sidebar">
	<div class="wrapper">
		<div class="nav">
		  <ul>
			<li><%= link_to 'Edit Deal','#edit_project_modal', :"data-toggle" => "modal" %></li>
			<li><%= link_to 'Add Note','#new_note_modal', :"data-toggle" => "modal" %></li>
			<% if @project.lost? || @project.won? || @project.hold? %>
			<li class="project" data-id="<%= @project.id %>">
				<%= link_to 'Reactivate Deal','#', :"data-state" => "reactivate", :class => "reactivate" %>
			</li>
			<% end %>
			<li><%= link_to 'Delete Deal', project_path, :method => "delete" %></li>
			<li><%= link_to raw('&#9666; Back to Deals'),projects_path %></li>
		  </ul>
		</div>
	</div>
</div>
<%= render :partial => "edit_modal" %>
<%= render :partial => "note_modal" %>