config/routes.rb
Zen::Application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => 'registrations'}
  
  resources :users, :only => [:show, :update]
  get 'account' => 'users#edit'
  get 'account/password' => 'users#password'
  get 'subscription' => "users#subscription"
  
  resources :projects do
    collection do
      get 'completed'
    end
    
    resources :transitions, :except => :destroy
  end
  
  resources :metrics, :only => :index

  root :to => 'site#index'

end

app/views/layouts/_flash.html.erb
<%= raw "<div class=\"alert notice\">#{notice}<a href=\"#\" data-dismiss=\"alert\" class=\"close\">&times;</a></div>" if notice %>
<%= raw "<div class=\"alert error\">#{alert}<a href=\"#\" data-dismiss=\"alert\" class=\"close\">&times;</a></div>" if alert %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zen</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>	
	<div id="header">
		<div class="container">
		<h1 id="logo"><%= link_to "Zen",projects_path %></h1>
		<ul id="nav">
		  <li><%= link_to t(:projects, :scope => "views.layout.app"), projects_path %></li>
		  <li><%= link_to t(:metrics, :scope => "views.layout.app"), metrics_path %></li>
		  <li><%= link_to t(:account, :scope => "views.layout.app"), account_path %></li>
		  <li><%= link_to t(:logout, :scope => "views.layout.app"), destroy_user_session_path, :method => :delete %></li>
		</ul>
		</div>
	</div>
	
	<%= render 'layouts/flash' %>
	
	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zen</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="site">
	
	<div id="header">
		<div class="container">
		<h1 id="logo"><%= link_to "Zen","/" %></h1>
		<ul id="nav">
		  <li><%= link_to t(:sign_up, :scope => "views.layout.site"), new_user_registration_path %></li>
		  <li><%= link_to t(:sign_in, :scope => "views.layout.site"), new_user_session_path %></li>
		</ul>
		</div>
	</div>
	
	<%= render 'layouts/flash' %>
	
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>